### ISSUE TITLE
Spinner indicator while loading and when waiting for page updates for "Don't ask again" across all DevHUB components

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-bos#689]
**Is your feature request related to a problem? Please describe.**
Through https://github.com/NEAR-DevHub/neardevhub-bos/pull/687 we already improved the UX for activity posts. Both the like and post buttons now have spinning indicators as long as the transaction goes on, and until the page contents are refreshed

**Describe the solution you'd like**
I would like to see the same UX across whole DevHub as it is now with Activity post. I would like it for: communities, discussions, blogs, the new proposals feature. I would also like to have developer documentations, with clear guidelines on how to create user friendly interactions when the "Don't ask again" feature is enabled. It is also needed for wallets confirming the transaction in a separate window, like Meteor wallet.

**Describe alternatives you've considered**
We know that this solution creates another issue for when transactions are confirmed manually. In the case where the user cancels sending the transaction, the spinners will still spin. To solve this, a callback method is needed in the VM like described here: https://github.com/NearSocial/VM/issues/105

```[tasklist]
### Tasks
- [X] [Community Discussions - Loading indicator when creating discussion and "Don't ask again" is enabled](https://github.com/NEAR-DevHub/neardevhub-bos/pull/691)
- [X] [Community Discussions -Disabling submit button, and adding spinner compose widget must not take effect for other components than those having an `isFinished` handler](https://github.com/NEAR-DevHub/neardevhub-bos/pull/691)
- [X] [Community Discussion - Clear discussion editor after transaction is complete](https://github.com/NEAR-DevHub/neardevhub-bos/pull/691)
- [X] [Community Discussion - Show posted discussion when transaction is complete ( don't require reload )](https://github.com/NEAR-DevHub/neardevhub-bos/pull/691)
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/824
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/825
- [X] [New Proposals - Submit draft](https://github.com/NEAR-DevHub/neardevhub-bos/pull/691)
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/826
```

**Comment by petersalomonsen** [comment]
See the first video of creating a discussion in the Pull request, and note that there's an issue on refreshing the feed ( up to 5 second delay ).
