### ISSUE TITLE
Introduce better URL paths / SEO optimization

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#724]
**Problem**
Currently, we don't have easy URL paths for DevHub content. Examples:

- Protocol Community: https://near.social/devhub.near/widget/app?page=community&handle=protocol
- Protocol Community About Tab: https://near.social/devhub.near/widget/app?page=community&handle=protocol&tab=about-us. Or 
- Blog article: https://near.social/devhub.near/widget/app?page=blog&id=3251

This makes it difficult to share links and optimize for SEO indexing.

**User Stories**

1. As a user, I want to have a memorable easy link so I can easily access and share DevHub content. Examples:
- Blog article: neardevhub.org/blog/article-slug (may need to introduce slug for blogs)
- Community: neardevhub.org/community/protocol
- Community About: neardevhub.org/community/protocol/about

2. As a user, I want to easily share links on social media platform and have the appropriate meta information displayed (e.g. DevHub image, title, description, etc).

3. As a DevHub user, I want to easily discover DevHub content on Google (e.g. https://developers.google.com/search/docs/crawling-indexing/special-tags).

**Acceptance Criteria**

```[tasklist]
### Tasks
- [x] web4 endpoint with social media links metadata and redirect ilnk ( https://github.com/NEAR-DevHub/neardevhub-contract/pull/111 )
- [x] social media links meta data should get titles and description from data stored in devhub contract
- [x] landing page showing the actual post/page linked to
- [x] links to open the page in near.social/near.org
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/827
- [x] proposal urls ( e.g. /proposal/1 )
- [x] community urls ( e.g. /community/webassemblymusic )
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/828
```

**Comment by frol** [comment]
Technical proposal:

1. Host a serverless [web4 app](https://web4.near.page/) that will serve HTTP traffic for https://devhub.near.page. [Example in Rust](https://github.com/frol/near-web4-demo)
2. For search bots and link previews: The app has to implement a custom routing to do a bit of server-side rendering, so URLs like `/communities/<handle>`, `/proposals` will serve HTML with SEO headers
3. For regular users: The app should render a simple preview of the page (an announcement, discussion, blog post, or proposal, similar to how Telegram does it, [open this link on browser](https://t.me/NEARDevHub/185)) and a BOS Gateway Selector, so the user can choose to be redirected to the relevant DevHub page on near.org or near.social
4. Introduce more "Share" buttons in the DevHub UI that will use https://devhub.near.page shortlinks

The rationale for using devhub.near.page over neardevhub.org is that we dogfood on using NEAR Web4 tech and we don't need to manage any other external services (we just need to extend our devhub contract).

**Comment by petersalomonsen** [comment]
Some example links:

- https://devhublink.testnet.page/community/webassemblymusic
- https://devhublink.testnet.page/community/chain-abstraction
- https://devhublink.testnet.page/proposal/3

**Comment by petersalomonsen** [comment]
Have a look at https://github.com/NEAR-DevHub/neardevhub-contract/pull/111 which resolves 6 of 8 tasks here.

**Comment by petersalomonsen** [comment]
I believe we can close this as we now have https://devhub.near.page

**Comment by ori-near** [comment]
> I believe we can close this as we now have https://devhub.near.page

Hi @petersalomonsen – it seems like we still don't have short URLs for things like communities:
/community/protocol. When I go to https://devhub.near.page and click on the protocol community, I see this long URL: https://devhub.near.page/devhub.near/widget/app?page=community&handle=protocol

**Comment by petersalomonsen** [comment]
> > I believe we can close this as we now have https://devhub.near.page
> 
> Hi @petersalomonsen – it seems like we still don't have short URLs for things like communities: /community/protocol. When I go to https://devhub.near.page and click on the protocol community, I see this long URL: https://devhub.near.page/devhub.near/widget/app?page=community&handle=protocol

Let's create separate issues for these places where it is missing. I'll add one for this particular case.

**Comment by petersalomonsen** [comment]
btw @ori-near we do in fact have the short URL https://devhub.near.page/community/protocol

It is just that the "copy link" button does not generate it, so I'll rephrase the new issue according to that.
