### ISSUE TITLE
Allow tracking of blog views

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#731]
# Problem
Currently, while DevHub offers communities the ability to use widgets such as blogs, our overlaps at form lacks basic analytics. This makes it difficult to understand user engagement with the content.

# User Story
As a community admin who leverages the blog widget, I want to be able to track and view basic analytics to understand how users are interacting with blog posts, so that I can make data-driven decisions about the content.

# Acceptance Criteria

- [x] Integrate basic website analytics tools (e.g. Google Analytics) or open-source alternative
- [x] Implement a dashboard for admins to view the data, including information such as:
  - [x] Total users/visitors
  - [x] Total Page views
  - [ ] Table showing blog title, number of unique visitors, average time spent on page
  - [ ] Visits by source
- [x] Allow admins to filter the data by time range

**Comment by petersalomonsen** [comment]
I'm looking into this with the following alternatives investigated

- **Google Analytics**: Because it is not possible to include the google analytics script on NearSocial, not even in an iframe, this is out of scope
- **NEAR transactions**: It is possible to provide function access keys with pre-paid gas allowance that are able to call a tracking method. The tracking call could be made from a hidden Iframe in to not disturb the user. This would allow to create statistics using NEAR indexer
- **Custom off-chain tracking**: It is possible to use an image, or a fetch call to an externally hosted service

**Comment by ori-near** [comment]
@petersalomonsen We agreed on our standup call today to change the scope for analytics for all of DevHub, not just blogs. And we should prioritize making the analytics available first to the DevHub team for MVP. For V2, we can provide analytics for each community as well. Also, we want to move as quickly as we can on this – so happy to go with an off the shelf solution here.

**Comment by petersalomonsen** [comment]
> @petersalomonsen We agreed on our standup call today to change the scope for analytics for all of DevHub, not just blogs. And we should prioritize making the analytics available first to the DevHub team for MVP. For V2, we can provide analytics for each community as well. Also, we want to move as quickly as we can on this – so happy to go with an off the shelf solution here.

@ori-near Check out ongoing progress here: https://github.com/NEAR-DevHub/neardevhub-bos/pull/756
