### ISSUE TITLE
RFP View

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#748]
# User Story
As an individual or team who wants to contribute to NEAR infrastructure, I want to view and interact with RFPs so that I can learn about specific requests and have a chance to submit a proposal.

# Acceptance Criteria
- [x] Verify that the UI implementation corresponds to the Figma design - [ ] **Header:** Users can see the RFP title, status, and creation date
  - [x] Status corresponds to the current stage (Accepting submissions, Evaluation, Selected, Canceled)
  - [x] Only admins can see the edit button at any given stage. Clicking edit will load the create/edit screen.
- [x] **RFP Comment:** The first RFP comment shows the information entered from the create RFP screen (e.g. Category, Summary, Description). Notes:
  - [x] The profile picture includes the RFP icon (not the author)
  - [x] The heading shows the author and when they created the RFP
- [ ] **Engage:** Logged in users can like and comment. All users can copy comment URL. For not logged users, show a log in button to comment/engage similar to DevHub proposals behavior.
- [x] **Logging:** Logs are created every time there is a new edit or activity on the RFP. The log includes the author who made the change (link to their profile), the event, and time stamp. 
  - [ ] Make sure to log every time a new proposal is linked or unlinked to an RFP, including the user who took the action.
  - [ ] Once a proposal was selected in an RFP, make sure to add a log that says it was the selected proposal both in the RFP and the respective proposal.
- [ ] **Right sidebar:** Displays submission deadline, timeline, selected proposal, and all proposals. If there are no proposals linked, display “None yet” text under Selected Proposal and All Proposals sections. Also display the count for the total number of proposals.

**Stage specific AC**
- [ ] **Accepting Submission:** During this stage, display a blue banner at the top of the page and below the comments section to encourage participants to respond to the proposal. Under the “All Proposals” section, show the statuses for any linked proposals.
- [ ] **Evaluation:** During this stage, do not allow any users to link RFPs to this proposal. And remove the blue banners with CTAs to submit a proposal. Continue to show the statuses for any linked proposals under “All Proposals” section. Allow any logged in users to continue to post comments.
- [ ] **Decision:** During this stage, do not allow any users to link RFPs to this proposal. And remove the blue banners with CTAs to submit a proposal. Under the “Selected Proposal(s)” section, show the selected proposal. Under the “All Proposals” section, only show the “Approved” status for the selected proposal, but do not show the statuses for all the other proposals. Allow any logged in users to continue to post comments. IF RPP is canceled, show the decision stage as gray.

# Attachments

See mock ups:

## Stage 1: Accepting Submission
![RFP-View-Stage1](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/11fcd381-5308-41e3-9c5e-8fb810e08a6f)

## Stage 2: Evaluation
![RFP-View-Stage2](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/67f896d7-117c-4127-b379-35771b05423d)

## Stage 3: Decision
![RFP-View-Stage3](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/6dfcf588-f5dd-427e-86ca-d2ba14d4134e)

**Comment by Megha-Dev-19** [comment]
Hey @ori-near, we discussed about hiding some proposals from "All proposals" list, I forgot to write it down, can you please confirm which were those, "Cancelled" and "Draft" state?

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 I think we decided to just hide cancelled ones ...
