### ISSUE TITLE
Add confirmations after editing proposal timeline with "Don't ask again" enabled

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-bos#800]
**Is your feature request related to a problem? Please describe.**
When approving a proposal with "Don't ask again" enabled there is no confirmation of the change.

The blue "sending transaction" toast is showing, but after the only indicator is the change of the status badge under the proposal title.

There should be a confirmation popup confirming that the change succeeded.

After that you also have to reload the page to see history entries for the change of the proposal state

<img width="516" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/9760441/98884996-6760-4ed7-be54-ca4cba03bbc6">

*No entries are added here without reloading the page*

The log should be updated with entries without having to reload.

**Describe the solution you'd like**
A confirmation toast should display after the change is effected, and the log should be updated with entries about changing of the proposal state.

# Tasks

- [x] add test case for approving a proposal with don't ask again enabled
- [x] Show confirmation toast after the change submission is successful
- [x] Update log entries without having to reload the page

**Comment by ori-near** [comment]
Thanks for fixing this, @petersalomonsen! Looks great.
