### ISSUE TITLE
Single Click Submit Button

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#804]
**Is your feature request related to a problem? Please describe.**

During discussions on the submit button of the blog addon. Ori and I concluded it would be easier for the user to not have to double click on draft/publish. Example: when creating a new blog the submit button states: DRAFT. To publish it you have to fold out the two options Submit as Draft or Publish. The user has to select one option, than click again on the button to actually do the action.

Since we decided to make it a single click, the user would expect to have the same behaviour when creating a proposal. 

**Describe the solution you'd like**
The proposals should have the same behaviour as the blog and on all portals. Events-committee, infrastructure-committee and devhub itself.

**Describe alternatives you've considered**
This type of behaviour could more easily be implemented after issue #777 would be finished but that would take too long for now.

Acceptance criteria:
- [x] Devhub proposal works the same way as the blog PR #805
- [x] Events committtee works the same way #808
- [x] Infrastructure committee works the same way [#20](https://github.com/NEAR-DevHub/near-prpsls-bos/pull/20)
