### ISSUE TITLE
Comment draft not cleared when reloading page after successful comment to a proposal

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-bos#876]
**Affected Portal:**
Select one: All

**Description:**
When commenting to a proposal, the comment editor is cleared, and the comment appears above it, just as is should. However, if you reload the page, the previous comment draft is back in the comment editor again.

**User Type:**
Specify: Regular User

**Reproduction Steps**

The issue is reproduced in the Playwright test in PR #875 

Here is a video reproducing the issue, notice that the comment comes back into the editor in the end:

https://github.com/user-attachments/assets/c1ac73a9-2389-4ae8-b869-ac9cd8cf4a60

**Expected behavior**
The comment editor should be cleared, also after reloading the page.

**Visual Reference**
If applicable, add screenshots or video recording to help explain your problem.

**Priority**
Select One: Medium (P2) – Major inconvenience

```[tasklist]
### Tasks
- [x] Reproduce issue in Playwright test
- [x] Implement fix for test
- [x] Apply fix and test in infrastructure-committee
- [x] Apply fix and test in events-committee ( depends on #843 )
```
