### ISSUE TITLE
Copy link button in communities should generate the short URLs

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-bos#882]
Referring to the comment from @ori-near here: https://github.com/NEAR-DevHub/neardevhub-bos/issues/724#issuecomment-2237141973

If you click the "Share button" in a community, for example at https://devhub.near.page/community/protocol, you get the URL https://near.social/devhub.near/widget/app?page=community&handle=protocol.

You should get the URL: https://devhub.near.page/community/protocol

The same goes for community announcements and comments, and possibly more within the community.

See https://github.com/NEAR-DevHub/neardevhub-bos/pull/858 and https://github.com/NEAR-DevHub/neardevhub-bos/pull/868 to see how the same feature was solved for proposals.
 
```[tasklist]
### Tasks
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/889
- [ ] https://github.com/NEAR-DevHub/neardevhub-bos/issues/908
- [ ] Clean URL in announcement comment share link button
- [ ] Clean URL in discussions "copy link to post" and "share on X/twitter" button (remove share by email button, and change twitter to X)
```

**Comment by ori-near** [comment]
Hi @petersalomonsen – I assume this ticket is not blocked, you just deprioritized it?

**Comment by petersalomonsen** [comment]
Thanks for reminding me @ori-near ,  I totally forgot about this one. It is not blocked :)
